language: rust

os:
- linux
- osx

rust:
- stable

cache:
- cargo

before_cache:
- rm -rf "$TRAVIS_HOME/.cargo/registry/src"

script:
  - cargo test --verbose --all
  - cargo build --verbose --all --release
  - mkdir -p tf-unused-${TRAVIS_OS_NAME}
  - cp target/release/tf-unused "./tf-unused-${TRAVIS_OS_NAME}"
  - tar czf "tf-unused-${TRAVIS_OS_NAME}.tar.gz" "./tf-unused-${TRAVIS_OS_NAME}"

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  skip_cleanup: true
  file_glob: true
  file: ./tf-unused-*.tar.gz
  on:
    tags: true